<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="failed"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.000">
  <properties />
            <testcase name="testGmailFunctionality" time="0.000" classname="com.epam.lab.FailLoginTest">
                <failure type="java.lang.RuntimeException"
                  message="java.io.FileNotFoundException: src\main\resources\credentials.csv (The system cannot find the path specified)"
              >
<![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: src\main\resources\credentials.csv (The system cannot find the path specified)
  org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
  org.testng.internal.Parameters.handleParameters(Parameters.java:429)
  org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
  org.testng.internal.Invoker.createParameters(Invoker.java:1075)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
  org.testng.SuiteRunner.run(SuiteRunner.java:254)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.io.FileNotFoundException: src\main\resources\credentials.csv (The system cannot find the path specified)
  java.io.FileInputStream.open0(Native Method)
  java.io.FileInputStream.open(FileInputStream.java:195)
  java.io.FileInputStream.<init>(FileInputStream.java:138)
  java.io.FileInputStream.<init>(FileInputStream.java:93)
  java.io.FileReader.<init>(FileReader.java:58)
  com.epam.lab.util.DataUtils.readDataFromCSVFile(DataUtils.java:71)
  com.epam.lab.FailLoginTest.getCredentials(FailLoginTest.java:31)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:135)
  org.testng.internal.Parameters.handleParameters(Parameters.java:429)
  org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
  org.testng.internal.Invoker.createParameters(Invoker.java:1075)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
  org.testng.SuiteRunner.run(SuiteRunner.java:254)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
